import { useRef, useState, type MouseEvent } from 'react'
import './theme.css'

type Lang = 'ru' | 'en' | 'vi'
type ChatMessage = { from: 'bot' | 'user'; text: string }

const translations = {
  ru: {
    nav:['Главная','Обо мне','Проекты','Контакты'], contact:'Связаться', code:'Код ↗', heroMicro:'01 — ГЛАВНАЯ', heroTitle:<>Создаю цифровые<br/><em>продукты, которые работают.</em></>, heroLead:'Павел Афанасьев — разработчик полного цикла с продуктовым фокусом. Проектирую и собираю веб, API, мобильные приложения и системы ИИ — от архитектуры до работающего выпуска.', viewProjects:'Смотреть проекты', discuss:'Обсудить проект', location:'Вьетнам · Россия', remote:'Удалённо',
    aboutLabel:'ОБО МНЕ', aboutEyebrow:'РАЗРАБОТЧИК ПОЛНОГО ЦИКЛА · СОЗДАТЕЛЬ ЦИФРОВЫХ ПРОДУКТОВ', aboutTitle:<>Работаю на стыке<br/><em>продукта и технологий.</em></>, aboutLead:'Проектирую и собираю продукты от интерфейса до сервера, данных и мобильного приложения. Люблю сложные системы, но делаю их понятными для пользователя.',
    servicesLabel:'УСЛУГИ', servicesTitle:<>Коммерческая<br/><em>разработка полного цикла.</em></>, servicesLead:'Задача, продуктовая логика, архитектура, интерфейс, интеграции и выпуск — в одном контуре.', projectsLabel:'ИЗБРАННЫЕ ПРОЕКТЫ', projectsTitle:<>Проекты<br/><em>в работе.</em></>, projectsLead:'Не просто карточки портфолио, а живые системы. Открывай репозиторий, чтобы посмотреть код и текущую реализацию.', learnLabel:'ИССЛЕДУЮ · СТРОЮ · ПОВТОРЯЮ', learnTitle:<>Исследую,<br/><em>строю, повторяю.</em></>, learnText:'Помимо коммерческой разработки, экспериментирую с ИИ-агентами, интерфейсами реального времени, компьютерным зрением, трёхмерной графикой и новыми способами взаимодействия человека с программой.', contactLabel:'КОНТАКТЫ', contactEyebrow:'ОТКРЫТ К СОТРУДНИЧЕСТВУ', contactTitle:<>Готов включиться<br/><em>в ваш проект.</em></>, contactText:'Продукт, стартап, команда или разовая задача. Могу взять разработку полного цикла или закрыть конкретный слой — интерфейс, API, мобильную сборку или ИИ-агента.', write:'Написать Павлу', top:'Наверх ↑', footer:'Разработка · ИИ · Продукты', statusDone:'Реализован', statusWork:'В разработке',
    chatTitle:'Павел · консультант', chatOpen:'Спросить об услугах', chatClose:'Закрыть чат', chatPlaceholder:'Напишите вопрос…', chatSend:'Отправить', chatWelcome:'Привет! Давайте обсудим наше сотрудничество. Здесь можно узнать об услугах, стоимости, сроках и формате работы.', chatServices:'Какие услуги?', chatPrice:'Сколько стоит?', chatTime:'Какие сроки?', chatProcess:'Как проходит работа?', chatContact:'Хочу обсудить проект',
    chatServicesAnswer:'Можно заказать лендинг, многостраничный сайт, веб-систему, API, мобильное приложение, AI-продукт или чат-бот. Также можно подключить меня к уже существующему проекту: архитектура, новые функции, интеграции и выпуск. Простые сайты начинаются с 10 000 ₽; дополнительные страницы, логотип, индивидуальный дизайн и анимация увеличивают стоимость.',
    chatPriceAnswer:'Стоимость начинается от 10 000 ₽ за простой лендинг. В базовый вариант входит сама разработка страницы; хостинг и дальнейшее администрирование не входят. Если проект простой, после завершения можно передать заказчику исходный код и все права. Если нужны логотип, несколько страниц, уникальный дизайн и анимация — стоимость повышается в зависимости от объёма и может доходить до уровня медианных цен российского рынка. Для ориентира: в 2026 году российские источники дают около 15–50 тыс. ₽ за типовой лендинг у частного разработчика и примерно 45–120 тыс. ₽ за индивидуальный дизайн; сложные анимированные проекты стоят существенно выше. Точную цену согласуем до начала работ.',
    chatTimeAnswer:'Простой лендинг обычно можно сделать за несколько дней. Более проработанный сайт — примерно 1–3 недели. Проекты с несколькими страницами, фирменным стилем, сложной анимацией, интеграциями или backend занимают больше времени. Срок фиксируется после согласования объёма.',
    chatProcessAnswer:'Сначала обсуждаем задачу, желаемый результат и материалы. Затем фиксируем объём и стоимость. После разработки показываю результат, вносим согласованные правки и передаю проект. Для простого проекта возможна передача исходного кода и всех прав; хостинг и постоянное администрирование оплачиваются отдельно, если они нужны.',
    chatContactAnswer:'Опишите продукт, основные функции, желаемый дизайн или пример, платформу и срок. Я помогу определить объём, вариант реализации и стоимость. Для быстрого контакта используйте кнопку «Написать Павлу».',
    chatFallback:'Могу рассказать об услугах, стоимости, сроках или процессе работы. Напишите вопрос своими словами.'
  },
  en: {
    nav:['Home','About','Projects','Contact'], contact:'Contact', code:'Code ↗', heroMicro:'01 — HOME', heroTitle:<>I create digital<br/><em>products that work.</em></>, heroLead:'Pavel Afanasyev — full-stack developer with a product focus. I design and build web, API, mobile applications and AI systems, from architecture to production.', viewProjects:'View projects', discuss:'Discuss a project', location:'Vietnam · Russia', remote:'Remote', aboutLabel:'ABOUT', aboutEyebrow:'FULL-STACK DEVELOPER · DIGITAL PRODUCT CREATOR', aboutTitle:<>Working where<br/><em>product meets technology.</em></>, aboutLead:'I design and build products from interface to server, data and mobile application. I like complex systems, but make them clear for the user.', servicesLabel:'SERVICES', servicesTitle:<>Full-cycle<br/><em>commercial development.</em></>, servicesLead:'Product logic, architecture, interface, integrations and delivery — in one workflow.', projectsLabel:'SELECTED PROJECTS', projectsTitle:<>Projects<br/><em>in progress.</em></>, projectsLead:'Not just portfolio cards, but live systems. Open a repository to see the code and current implementation.', learnLabel:'RESEARCH · BUILD · REPEAT', learnTitle:<>Research,<br/><em>build, repeat.</em></>, learnText:'Beyond commercial development, I experiment with AI agents, real-time interfaces, computer vision, 3D graphics and new ways for people to interact with software.', contactLabel:'CONTACT', contactEyebrow:'OPEN TO COLLABORATION', contactTitle:<>Ready to join<br/><em>your project.</em></>, contactText:'A product, startup, team or one-off task. I can take full-cycle development or own a specific layer — interface, API, mobile build or AI agent.', write:'Write to Pavel', top:'Back to top ↑', footer:'Development · AI · Products', statusDone:'Completed', statusWork:'In development', chatTitle:'Pavel · project advisor', chatOpen:'Ask about services', chatClose:'Close chat', chatPlaceholder:'Ask a question…', chatSend:'Send', chatWelcome:'Hi! Let’s discuss working together. You can ask about services, pricing, timelines and the delivery process.', chatServices:'Services', chatPrice:'Pricing', chatTime:'Timelines', chatProcess:'How it works', chatContact:'Discuss my project',
    chatServicesAnswer:'You can order a landing page, multi-page website, web system, API, mobile application, AI product or chatbot. I can also join an existing project for architecture, new features, integrations and release work. Simple websites start from RUB 10,000; extra pages, a logo, custom design and animation increase the price.',
    chatPriceAnswer:'Pricing starts from RUB 10,000 for a simple landing page. The basic price covers the development itself; hosting and ongoing administration are not included. For a simple project, the source code and all rights can be transferred to the client after completion. If you need a logo, multiple pages, custom design and animation, the price increases with scope and can reach the level of Russian market median pricing. As a 2026 benchmark, Russian sources put a typical private-developer landing page around RUB 15k–50k and custom-design work around RUB 45k–120k, with complex animated projects substantially higher. The exact quote is agreed before work starts.',
    chatTimeAnswer:'A simple landing page can usually be delivered within several days. A more polished website typically takes about 1–3 weeks. Multiple pages, branding, complex animation, integrations or backend work require more time. The schedule is fixed after the scope is agreed.',
    chatProcessAnswer:'We start by discussing the goal, expected result and available materials. Then scope and price are fixed. I build the project, show the result, apply agreed revisions and hand it over. For a simple project, source code and full rights can be transferred; hosting and ongoing administration are separate if needed.',
    chatContactAnswer:'Describe the product, key features, preferred design or reference, platform and desired deadline. I’ll help define the scope, implementation approach and price. For direct contact, use “Write to Pavel”.', chatFallback:'I can explain services, pricing, timelines or the delivery process. Ask your question in your own words.'
  },
  vi: {
    nav:['Trang chủ','Giới thiệu','Dự án','Liên hệ'], contact:'Liên hệ', code:'Mã nguồn ↗', heroMicro:'01 — TRANG CHỦ', heroTitle:<>Tôi tạo ra các<br/><em>sản phẩm số hiệu quả.</em></>, heroLead:'Pavel Afanasyev — lập trình viên full-stack tập trung vào sản phẩm. Tôi thiết kế và xây dựng web, API, ứng dụng di động và hệ thống AI, từ kiến trúc đến triển khai.', viewProjects:'Xem dự án', discuss:'Trao đổi dự án', location:'Việt Nam · Nga', remote:'Từ xa', aboutLabel:'GIỚI THIỆU', aboutEyebrow:'LẬP TRÌNH VIÊN FULL-STACK · NHÀ SÁNG TẠO SẢN PHẨM SỐ', aboutTitle:<>Kết nối giữa<br/><em>sản phẩm và công nghệ.</em></>, aboutLead:'Tôi thiết kế và xây dựng sản phẩm từ giao diện đến máy chủ, dữ liệu và ứng dụng di động. Hệ thống có thể phức tạp, nhưng trải nghiệm phải rõ ràng.', servicesLabel:'DỊCH VỤ', servicesTitle:<>Phát triển<br/><em>thương mại trọn gói.</em></>, servicesLead:'Logic sản phẩm, kiến trúc, giao diện, tích hợp và triển khai — trong một quy trình.', projectsLabel:'DỰ ÁN TIÊU BIỂU', projectsTitle:<>Các dự án<br/><em>đang triển khai.</em></>, projectsLead:'Không chỉ là hồ sơ năng lực, mà là các hệ thống thực tế. Mở kho mã để xem mã nguồn và tiến độ hiện tại.', learnLabel:'NGHIÊN CỨU · XÂY DỰNG · LẶP LẠI', learnTitle:<>Nghiên cứu,<br/><em>xây dựng, lặp lại.</em></>, learnText:'Ngoài phát triển thương mại, tôi thử nghiệm với AI agent, giao diện thời gian thực, thị giác máy tính, đồ họa 3D và những cách mới để con người tương tác với phần mềm.', contactLabel:'LIÊN HỆ', contactEyebrow:'SẴN SÀNG HỢP TÁC', contactTitle:<>Sẵn sàng tham gia<br/><em>dự án của bạn.</em></>, contactText:'Sản phẩm, startup, đội ngũ hoặc một nhiệm vụ cụ thể. Tôi có thể đảm nhận toàn bộ quy trình hoặc một lớp riêng — giao diện, API, mobile hoặc AI agent.', write:'Viết cho Pavel', top:'Lên đầu trang ↑', footer:'Phát triển · AI · Sản phẩm', statusDone:'Đã hoàn thành', statusWork:'Đang phát triển', chatTitle:'Pavel · tư vấn dự án', chatOpen:'Hỏi về dịch vụ', chatClose:'Đóng chat', chatPlaceholder:'Nhập câu hỏi…', chatSend:'Gửi', chatWelcome:'Xin chào! Hãy cùng trao đổi về việc hợp tác. Bạn có thể hỏi về dịch vụ, chi phí, thời gian và quy trình triển khai.', chatServices:'Dịch vụ', chatPrice:'Chi phí', chatTime:'Thời gian', chatProcess:'Quy trình', chatContact:'Trao đổi dự án',
    chatServicesAnswer:'Bạn có thể đặt landing page, website nhiều trang, hệ thống web, API, ứng dụng di động, sản phẩm AI hoặc chatbot. Tôi cũng có thể tham gia dự án hiện có về kiến trúc, tính năng mới, tích hợp và phát hành. Website đơn giản bắt đầu từ 10.000 RUB; thêm trang, logo, thiết kế riêng và animation sẽ làm tăng chi phí.',
    chatPriceAnswer:'Chi phí bắt đầu từ 10.000 RUB cho một landing page đơn giản. Mức cơ bản chỉ bao gồm phát triển; hosting và quản trị thường xuyên không bao gồm. Với dự án đơn giản, có thể bàn giao mã nguồn và toàn bộ quyền cho khách hàng sau khi hoàn thành. Nếu cần logo, nhiều trang, thiết kế riêng và animation, chi phí tăng theo phạm vi và có thể đạt mức giá trung vị của thị trường Nga. Theo các mức tham khảo năm 2026, landing page phổ biến của freelancer tại Nga khoảng 15–50 nghìn RUB, còn thiết kế riêng khoảng 45–120 nghìn RUB; dự án animation phức tạp có thể cao hơn đáng kể. Báo giá chính xác được thống nhất trước khi bắt đầu.',
    chatTimeAnswer:'Landing page đơn giản thường có thể hoàn thành trong vài ngày. Website được đầu tư kỹ hơn thường mất khoảng 1–3 tuần. Nhiều trang, nhận diện thương hiệu, animation phức tạp, tích hợp hoặc backend sẽ cần thêm thời gian. Thời gian được chốt sau khi thống nhất phạm vi.',
    chatProcessAnswer:'Bắt đầu bằng việc trao đổi mục tiêu, kết quả mong muốn và tài liệu có sẵn. Sau đó chốt phạm vi và chi phí. Tôi xây dựng, trình bày kết quả, thực hiện các chỉnh sửa đã thống nhất và bàn giao. Với dự án đơn giản, có thể bàn giao mã nguồn và toàn bộ quyền; hosting và quản trị liên tục được tính riêng nếu cần.',
    chatContactAnswer:'Hãy mô tả sản phẩm, chức năng chính, phong cách hoặc mẫu tham khảo, nền tảng và thời hạn mong muốn. Tôi sẽ giúp xác định phạm vi, cách triển khai và chi phí. Để liên hệ trực tiếp, hãy chọn “Viết cho Pavel”.', chatFallback:'Tôi có thể giải thích về dịch vụ, chi phí, thời gian hoặc quy trình. Hãy đặt câu hỏi theo cách của bạn.'
  }
} as const

const projects=[
 {number:'01',category:'Образование · Дети',title:'Я-Зарядка ИИ',status:'Реализован',text:'Игровая система для ежедневной зарядки детей 5–14 лет: карта мира, миссии, награды и семейные челленджи.',tags:['Веб','ИИ','RuStore'],href:'https://github.com/paulafanasyev/ya-zaryadka-ai'},
 {number:'02',category:'Образование · ИИ',title:'ИИ-репетитор английского и математики',status:'Реализован',text:'Триязычный ИИ-репетитор RU / EN / VI с шестью ИИ-учителями, голосом, аватарами, уроками и мини-играми.',tags:['React','Node','Prisma'],href:'https://github.com/paulafanasyev/ai-english-teacher'},
 {number:'03',category:'Социальное · Перевод',title:'Мост · Два Сердца',status:'Реализован',text:'Кросс-культурная платформа Китай — Россия с голосовым переводом, совместимостью анкет и тремя языками.',tags:['React','Express','WebSocket'],href:'https://github.com/paulafanasyev/bridges'},
 {number:'04',category:'Поиск · Аналитика',title:'Глаз Бога',status:'В разработке',text:'Интеллектуальный поиск и аналитика по открытым источникам: агрегация публичных данных, быстрые запросы и понятный интерфейс.',tags:['Python','API','Telegram'],href:'https://github.com/paulafanasyev'},
 {number:'05',category:'Платформа · Общественные сервисы',title:'Мир Самозанятых',status:'В разработке',text:'Продуктовая линейка АНО ЦПС: веб, мобильный клиент и серверная часть, сервисы поддержки сообщества и контур ИИ.',tags:['Python','TypeScript','Flutter'],href:'https://github.com/paulafanasyev/mir-samozanyatykh-'},
 {number:'06',category:'ИИ-агент · Аватар',title:'Светлана',status:'В разработке',text:'Русскоязычный ИИ-агент и реалистичный аватар Светлана для веба и Android: управление устройством, память, файлы и расписания.',tags:['TypeScript','Android','MCP'],href:'https://github.com/paulafanasyev/Mobile-agent-russkiy-termuxMCP-OX'}
]
const services=[['01','Разработка веб-систем','Веб и API под ключ: React, Node, PostgreSQL, PWA, размещение и сопровождение.'],['02','Продукты с ИИ','ИИ-агенты, голосовые интерфейсы, языковые модели, MCP, аватары и продуктовые кабинеты.'],['03','Мобильные приложения','Capacitor, Flutter и Android: от прототипа до сборки и выпуска.'],['04','Подключение к существующему проекту','Архитектура, новые функции, интеграции, выпуск и поддержка команды.']]

function ProjectCard({project,lang}:{project:typeof projects[number],lang:Lang}){
 const ref=useRef<HTMLAnchorElement>(null); const [spot,setSpot]=useState({x:50,y:50}); const t=translations[lang]; const i=Number(project.number)-1
 const move=(e:MouseEvent<HTMLAnchorElement>)=>{const n=ref.current,r=n?.getBoundingClientRect();if(!n||!r)return;const x=((e.clientX-r.left)/r.width)*100,y=((e.clientY-r.top)/r.height)*100;setSpot({x,y});n.style.setProperty('--mx',`${(x-50)/28}px`);n.style.setProperty('--my',`${(y-50)/28}px`)}
 const localizedCategories=lang==='en'?['Education · Children','Education · AI','Social · Translation','Search · Analytics','Platform · Public Services','AI Agent · Avatar']:lang==='vi'?['Giáo dục · Trẻ em','Giáo dục · AI','Xã hội · Dịch thuật','Tìm kiếm · Phân tích','Nền tảng · Dịch vụ cộng đồng','AI Agent · Avatar']:projects.map(p=>p.category)
 const localizedTitles=lang==='en'?['AI Kids Workout','AI English & Math Tutor','Bridge · Two Hearts','God’s Eye','Self-Employed World','Svetlana']:lang==='vi'?['AI Vận động trẻ em','Gia sư AI Anh văn & Toán','Cầu nối · Hai trái tim','God’s Eye','Thế giới người tự doanh','Svetlana']:projects.map(p=>p.title)
 const texts=lang==='en'?['A game system for daily workouts for children aged 5–14: world map, missions, rewards and family challenges.','Trilingual AI tutor RU / EN / VI with six AI teachers, voice, avatars, lessons and mini-games.','Cross-cultural China–Russia platform with voice translation, profile compatibility and three languages.','Intelligent search and analytics across open sources: public-data aggregation, fast queries and a clear interface.','Product line of the Center for Self-Employed Support: web, mobile and server services with an AI layer.','Russian-speaking AI agent and realistic avatar Svetlana for web and Android: device control, memory, files and schedules.'][i]:lang==='vi'?['Hệ thống trò chơi luyện tập hằng ngày cho trẻ 5–14 tuổi: bản đồ thế giới, nhiệm vụ, phần thưởng và thử thách gia đình.','Gia sư AI ba ngôn ngữ RU / EN / VI với sáu giáo viên AI, giọng nói, avatar, bài học và mini-game.','Nền tảng kết nối Trung Quốc–Nga với dịch giọng nói, tương thích hồ sơ và ba ngôn ngữ.','Tìm kiếm và phân tích thông minh từ nguồn mở: tổng hợp dữ liệu công khai, truy vấn nhanh và giao diện rõ ràng.','Hệ sinh thái sản phẩm hỗ trợ người tự doanh: web, mobile, máy chủ và lớp AI.','AI agent nói tiếng Nga và avatar Svetlana cho web và Android: điều khiển thiết bị, bộ nhớ, tệp và lịch.'][i]:project.text
 const status=project.status==='Реализован'?t.statusDone:t.statusWork
 return <a ref={ref} className="projectCard" href={project.href} target="_blank" rel="noreferrer" onMouseMove={move} onMouseLeave={()=>setSpot({x:50,y:50})}><div className="projectIndex">{project.number}</div><div className="projectMain"><div className="projectMeta"><span>{localizedCategories[i]}</span><span>{status}</span></div><h3>{localizedTitles[i]}</h3><p>{texts}</p><div className="tags">{project.tags.map(tag=><span key={tag}>{lang==='en'&&tag==='Веб'?'Web':lang==='en'&&tag==='ИИ'?'AI':lang==='vi'&&tag==='Веб'?'Web':lang==='vi'&&tag==='ИИ'?'AI':tag}</span>)}</div></div><div className="projectArrow">↗</div><div className="projectLight" style={{left:`${spot.x}%`,top:`${spot.y}%`}}/></a>
}

function App(){
 const [menu,setMenu]=useState(false); const [lang,setLang]=useState<Lang>(()=>{const saved=localStorage.getItem('site-lang');return saved==='en'||saved==='vi'?saved:'ru'}); const t=translations[lang]; const [chatOpen,setChatOpen]=useState(false); const [chatInput,setChatInput]=useState(''); const [chatMessages,setChatMessages]=useState<ChatMessage[]>([{from:'bot',text:t.chatWelcome}])
 const changeLang=(next:Lang)=>{setLang(next);localStorage.setItem('site-lang',next);setMenu(false);setChatMessages([{from:'bot',text:translations[next].chatWelcome}])}
 const answerFor=(topic:string,replyLang:Lang)=>{const rt=translations[replyLang];return topic==='services'?rt.chatServicesAnswer:topic==='price'?rt.chatPriceAnswer:topic==='time'?rt.chatTimeAnswer:topic==='process'?rt.chatProcessAnswer:topic==='contact'?rt.chatContactAnswer:rt.chatFallback}
 const detectLang=(text:string):Lang=>{if(/[а-яё]/i.test(text))return 'ru';if(/[àáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]/i.test(text))return 'vi';return 'en'}
 const sendChat=(preset?:string,topic?:string)=>{const text=(preset??chatInput).trim();if(!text)return;const lower=text.toLowerCase();const detected=topic??(/стоим|цен|сколько|price|cost|pricing|chi phí|giá/.test(lower)?'price':/срок|когда|долго|timeline|deadline|how long|thời gian|bao lâu/.test(lower)?'time':/услуг|дела|можете|service|what do you do|dịch vụ/.test(lower)?'services':/как работ|процесс|process|how it works|quy trình/.test(lower)?'process':/проект|связ|contact|discuss|dự án|liên hệ/.test(lower)?'contact':'fallback');const replyLang=topic?lang:detectLang(text);const response=answerFor(detected,replyLang);setChatMessages(p=>[...p,{from:'user',text},{from:'bot',text:response}]);setChatInput('')}
 return <main className={`site lang-${lang}`} id="top"><iframe className="radiantBackground" src="https://radiant-shaders.com/flow-field" title="Flow Field background" loading="eager" aria-hidden="true" tabIndex={-1}/>
 <header className="nav shell"><a className="brand" href="#top">PAVEL AFANASYEV</a><nav className={menu?'navlinks open':'navlinks'}>{t.nav.map((item,i)=><a key={item} href={['#top','#about','#projects','#contact'][i]} onClick={()=>setMenu(false)}>{item}</a>)}</nav><div className="navRight"><div className="languageSwitch" aria-label="Language"><button className={lang==='ru'?'active':''} onClick={()=>changeLang('ru')}>RU</button><button className={lang==='en'?'active':''} onClick={()=>changeLang('en')}>EN</button><button className={lang==='vi'?'active':''} onClick={()=>changeLang('vi')}>VI</button></div><a className="githubLink" href="https://github.com/paulafanasyev" target="_blank" rel="noreferrer">{t.code}</a><a className="contactPill" href="#contact">{t.contact}</a><button className="menuButton" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?'×':'☰'}</button></div></header>
 <section className="hero shell"><div className="heroCopy"><p className="micro">{t.heroMicro}</p><h1>{t.heroTitle}</h1><p className="lead">{t.heroLead}</p><div className="heroActions"><a className="primaryButton" href="#projects">{t.viewProjects} <span>↓</span></a><a className="ghostButton" href="#contact">{t.discuss} <span>↗</span></a></div></div><div className="heroFoot"><span>{t.location}</span><span>{t.remote}</span><span>© 2026</span></div></section>
 <section id="about" className="section shell about"><div className="sectionLabel"><span>02</span><span>{t.aboutLabel}</span></div><div className="aboutIntro"><p className="eyebrow">{t.aboutEyebrow}</p><h2>{t.aboutTitle}</h2><p className="aboutLead">{t.aboutLead}</p></div><div className="aboutGrid"><div className="aboutText"><p>{lang==='ru'?'Работаю с React, Node, TypeScript, Python, PostgreSQL, PWA и мобильными технологиями. Веду проекты удалённо между Вьетнамом и Россией.':lang==='en'?'I work with React, Node, TypeScript, Python, PostgreSQL, PWA and mobile technologies. I run projects remotely between Vietnam and Russia.':'Tôi làm việc với React, Node, TypeScript, Python, PostgreSQL, PWA và công nghệ di động. Tôi triển khai dự án từ xa giữa Việt Nam và Nga.'}</p><p>{lang==='ru'?'На коммерческой основе выполняю разработку полного цикла: первые версии продуктов, развитие существующих систем, модули ИИ и интеграции. Могу подключиться к чужому проекту как исполнитель или партнёр по архитектуре.':lang==='en'?'I provide full-cycle commercial development: first product versions, existing-system development, AI modules and integrations. I can join as an implementation partner or architecture partner.':'Tôi cung cấp phát triển thương mại trọn gói: phiên bản đầu tiên, phát triển hệ thống hiện có, module AI và tích hợp. Tôi có thể tham gia với vai trò thực thi hoặc đối tác kiến trúc.'}</p></div><div className="factGrid"><div><b>{lang==='ru'?'Организация':lang==='en'?'Organization':'Tổ chức'}</b><span>Мир Самозанятых</span></div><div><b>{lang==='ru'?'Формат':lang==='en'?'Format':'Hình thức'}</b><span>{t.remote}</span></div><div><b>{lang==='ru'?'Фокус':lang==='en'?'Focus':'Trọng tâm'}</b><span>Web · AI · Mobile</span></div></div></div></section>
 <section id="services" className="section shell services"><div className="sectionLabel"><span>03</span><span>{t.servicesLabel}</span></div><div className="sectionHeading"><h2>{t.servicesTitle}</h2><p>{t.servicesLead}</p></div><div className="serviceList">{services.map(([number,title,text])=><article className="serviceRow" key={number}><span className="serviceNumber">{number}</span><div><h3>{lang==='en'?['Web systems development','AI products','Mobile applications','Joining an existing project'][Number(number)-1]:lang==='vi'?['Phát triển hệ thống web','Sản phẩm AI','Ứng dụng di động','Tham gia dự án hiện có'][Number(number)-1]:title}</h3><p>{lang==='en'?['Web and API development: React, Node, PostgreSQL, PWA, deployment and support.','AI agents, voice interfaces, language models, MCP, avatars and product dashboards.','Capacitor, Flutter and Android: from prototype to build and release.','Architecture, new features, integrations, release and team support.'][Number(number)-1]:lang==='vi'?['Web và API trọn gói: React, Node, PostgreSQL, PWA, triển khai và hỗ trợ.','AI agent, giao diện giọng nói, mô hình ngôn ngữ, MCP, avatar và dashboard sản phẩm.','Capacitor, Flutter và Android: từ prototype đến build và phát hành.','Kiến trúc, tính năng mới, tích hợp, phát hành và hỗ trợ đội ngũ.'][Number(number)-1]:text}</p></div><span className="serviceArrow">↗</span></article>)}</div></section>
 <section id="projects" className="section shell projects"><div className="sectionLabel"><span>04</span><span>{t.projectsLabel}</span></div><div className="sectionHeading"><h2>{t.projectsTitle}</h2><p>{t.projectsLead}</p></div><div className="projectGrid">{projects.map(p=><ProjectCard key={p.number} project={p} lang={lang}/>)}</div></section>
 <section className="section shell learn"><div className="sectionLabel"><span>05</span><span>{t.learnLabel}</span></div><div className="learnGrid"><div><h2>{t.learnTitle}</h2></div><p>{t.learnText}</p></div></section>
 <section className="cta shell" id="contact"><div className="sectionLabel light"><span>06</span><span>{t.contactLabel}</span></div><div className="ctaInner"><div><p className="micro lightText">{t.contactEyebrow}</p><h2>{t.contactTitle}</h2></div><div className="ctaSide"><p>{t.contactText}</p><a className="ctaButton" href="mailto:pavel.afanadyev@inbox.ru">{t.write} <span>↗</span></a></div></div></section>
 <footer className="footer shell"><div className="footerBrand">PAVEL AFANASYEV</div><div>© 2026 · {t.footer}</div><div>{t.location} · {lang==='ru'?'удалённо':lang==='en'?'remote':'từ xa'}</div><a href="#top">{t.top}</a></footer>
 <button className="chatLauncher" onClick={()=>setChatOpen(!chatOpen)} aria-label={chatOpen?t.chatClose:t.chatOpen}><span className="chatLauncherDot"/>{chatOpen?'×':'AI'}</button>
 {chatOpen&&<aside className="clientChat" aria-label={t.chatTitle}><div className="clientChatHead"><div><strong>{t.chatTitle}</strong><small>{t.location} · {t.remote}</small></div><button onClick={()=>setChatOpen(false)} aria-label={t.chatClose}>×</button></div><div className="clientChatBody">{chatMessages.map((m,i)=><div className={`chatBubble ${m.from}`} key={`${i}-${m.text}`}>{m.text}</div>)}</div><div className="chatQuick"><button onClick={()=>sendChat(t.chatServices,'services')}>{t.chatServices}</button><button onClick={()=>sendChat(t.chatPrice,'price')}>{t.chatPrice}</button><button onClick={()=>sendChat(t.chatTime,'time')}>{t.chatTime}</button><button onClick={()=>sendChat(t.chatProcess,'process')}>{t.chatProcess}</button><button onClick={()=>sendChat(t.chatContact,'contact')}>{t.chatContact}</button></div><form className="chatForm" onSubmit={e=>{e.preventDefault();sendChat()}}><input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder={t.chatPlaceholder} aria-label={t.chatPlaceholder}/><button type="submit">{t.chatSend}</button></form></aside>}
 </main>
}
export default App
